In [1]:
import pandas as pd
import numpy as np

# Control data

The purpose of this workbook is to extract potential controls from both the EPO and the PCT specifications. This ensures that there is no overlap between the EPO and PCT controls so that a potential patent may appear in the controls twice, as this may otherwise bias the results. The final potential is combined across both the EPO and the PCT, used in the creating_EPO/PCT_control workbooks.

### EPO potential citations

In [2]:
#read in both the firm and individual data
EPO_ind_data = pd.read_csv("Patents data/202001_EPO_Inv_reg.txt", sep= "|", header = 0)
EPO_firm_data = pd.read_csv("Patents data/202001_EPO_App_reg.txt", sep = "|", header = 0)

In [3]:
#drop any unecessary rows from the data 
EPO_ind_data.drop(["pub_nbr", "person_id", "inv_name", "address", "reg_code",
                   "ctry_code", "reg_share", "inv_share"], axis = 1, inplace = True)

In [4]:
#drop any unecessary rows from the data
EPO_firm_data.drop(["pub_nbr", "person_id", "app_name", "address", "reg_code",
                   "ctry_code", "reg_share", "app_share"], axis = 1, inplace = True)

In [5]:
#get a list of all app numbers from the both EPOs
#use set to make sure there are no duplicates
EPO_all_app_nbr = list(set(list(EPO_ind_data["app_nbr"]) + list(EPO_firm_data["app_nbr"])))

In [6]:
#drop the app nbr code as the IPC code only contains appln_id which it will be merged on
EPO_firm_data.drop(["app_nbr"], axis = 1, inplace = True)
EPO_ind_data.drop(["app_nbr"], axis = 1, inplace = True)

In [7]:
#check to make sure that no data has been dropped
EPO_firm_data.count()

appln_id    3784463
dtype: int64

In [8]:
#list all the firm id's
EPO_firm_list = list(EPO_firm_data["appln_id"])

In [9]:
#see if there are any ids in individual data that are not the same in the individual id
EPO_inv_unique = EPO_ind_data[~EPO_ind_data["appln_id"].isin(EPO_firm_list)]

In [10]:
#output the results of the difference
EPO_inv_unique

          appln_id
84171        95006
181381      153738
217928      169818
217929      169818
217930      169818
304289      212280
357396      233507
357397      233507
357398      233507
360161      234485
360162      234485
360163      234485
464005      289148
464006      289148
464007      289148
509018      304697
509019      304697
509020      304697
509021      304697
509022      304697
518440      307815
518441      307815
518442      307815
518443      307815
518444      307815
518445      307815
518446      307815
570573      328679
570574      328679
570575      328679
...            ...
6577069  352501719
6577070  352501719
6577071  352501719
6577072  352501719
6577073  352501719
6577074  352501719
6577075  352501719
6577076  352501719
6765250  375252472
6910610  380487899
6914947  380646466
6914948  380646466
6914949  380646466
6914950  380646466
6921102  380717488
6991620  405324854
6991621  405324854
6991622  405324854
7310113  414237384
7326933  414765951
7326934  414765951
7326935  414765951
7464412  418611548
7529413  420441565
7567599  421458931
7567600  421458931
7567601  421458931
7567602  421458931
7567603  421458931
7567604  421458931

[294 rows x 1 columns]

In [11]:
#repeat the same for the firm data
EPO_ind_list = list(EPO_ind_data["appln_id"])

In [12]:
#it appears that the firms have 10,000 extra application ids
EPO_firm_unique = EPO_firm_data[~EPO_firm_data["appln_id"].isin(EPO_ind_list)]
EPO_firm_unique

          appln_id
592            618
2696          2773
2933          3011
3032          3116
3034          3118
3114          3202
3160          3277
3247          3407
3254          3416
3336          3516
3340          3520
3341          3521
3356          3540
3384          3575
3428          3630
3477          3687
3716          3982
3728          3998
3923          4206
3930          4213
3931          4214
3978          4265
3985          4276
4721          5016
4722          5016
4895          5318
4965          5448
4981          5480
4987          5488
4988          5490
...            ...
3764986  498861676
3764992  498861692
3765950  499310857
3765951  499310857
3766720  499582646
3767419  499892407
3767420  499892407
3767829  500040265
3769574  500606326
3771396  501450434
3772335  501726446
3772746  501870500
3774515  502484088
3776134  503136240
3776165  503136271
3776211  503136509
3776392  503315791
3776573  503372138
3776574  503372140
3777244  503613701
3777248  503614035
3777686  503714696
3777691  503714720
3778155  503985396
3778640  504125105
3780665  504854833
3780666  504854833
3782407  505752410
3783592  506922230
3784327  508645821

[10518 rows x 1 columns]

In [13]:
#get a list of all application id's
all_EPO_list = set(EPO_ind_list + EPO_firm_list)

In [14]:
#check the length of this list
len(all_EPO_list)

3507391

In [15]:
#create a dataframe of this list
all_EPO = pd.DataFrame(all_EPO_list)

In [16]:
all_EPO.rename(columns = {0: "appln_id"}, inplace = True)

In [17]:
all_EPO

         appln_id
0        16777216
1               1
2               2
3               3
4               4
5               5
6               6
7               7
8               8
9               9
10             10
11             11
12             12
13             13
14             14
15             15
16             16
17             17
18             18
19             19
20             20
21             21
22             22
23             23
24             24
25             25
26             26
27             27
28             28
29             29
...           ...
3507361  16777177
3507362  16777178
3507363  16777179
3507364  16777180
3507365  16777181
3507366  16777182
3507367  16777183
3507368  16777184
3507369  16777185
3507370  16777186
3507371  16777187
3507372  16777188
3507373  16777189
3507374  16777190
3507375  16777191
3507376  16777192
3507377  16777193
3507378  16777194
3507379  16777195
3507380  16777196
3507381  16777197
3507382  16777198
3507383  16777199
3507384  16777200
3507385  16777201
3507386  16777202
3507387  16777203
3507388  16777204
3507389  16777205
3507390  16777206

[3507391 rows x 1 columns]

In [18]:
#read in the IPC dataframe that includes prio_ye IPC
EPO_IPC = pd.read_csv("Patents data/202001_EPO_IPC.txt", sep = "|", header = 0)

In [19]:
#using the definition that the first IPC code is the primary code
#extract the first IPC code associated with that appln_id
def first(s):
    return s.iloc[0]
    
IPC_first = EPO_IPC.groupby(["appln_id"]).agg(first)

In [21]:
#merge the EPO data with the IPC code data
all_EPO_IPC = all_EPO.merge(IPC_first, on="appln_id")

In [22]:
#count the results
all_EPO_IPC.count()

appln_id     3507391
prio_year    3507391
app_year     3507391
IPC          3505684
dtype: int64

### PCT potential citations

In [23]:
#read in all PCT information
EPO_PCT = pd.read_csv("Patents data/202001_EPO_PCT.txt", sep = "|", header = 0)
PCT_firm = pd.read_csv("Patents data/202001_PCT_App_reg.txt", sep = "|", header = 0)
PCT_ind = pd.read_csv("Patents data/202001_PCT_Inv_reg.txt", sep = "|", header = 0)
PCT_IPC = pd.read_csv("Patents data/202001_PCT_IPC.txt", sep = "|", header = 0)

In [24]:
#check the number of codes that cross both EPO and PCT boundaries
EPO_PCT.count()

app_nbr    3549526
pct_nbr    3549526
dtype: int64

In [25]:
#count the number of IPC codes
PCT_IPC.count()

pct_nbr      12601935
prio_year    12601935
app_year     12601935
IPC          12599616
dtype: int64

In [26]:
#drop any unecessary information from the firm database
PCT_firm.drop(["internat_appln_nr", "appln_id","app_name", "address", "reg_code", "ctry_code",
              "reg_share", "app_share"], axis = 1, inplace=True)

In [27]:
#drop any unecessary information from the individual database
PCT_ind.drop(["internat_appln_nr", "appln_id","inv_name", "address", "reg_code", "ctry_code",
              "reg_share", "inv_share"], axis = 1, inplace=True)

In [28]:
#create a dataframe of all the pct_nbr's 
PCT_all = pd.DataFrame(set(list(PCT_firm["pct_nbr"]) + list(PCT_ind["pct_nbr"])))

In [29]:
#rename the column to pct_nbr
PCT_all.rename(columns = {0: "pct_nbr"},inplace = True)

In [30]:
#remove all results that appear in the EPO dataframe above
PCT_EPO_notEPO = EPO_PCT[~EPO_PCT["app_nbr"].isin(EPO_all_app_nbr)]

In [31]:
#we want PCT applications that also progress to the EPO but do not appear in the EPO data above
#first of all create a list of all pct_nbr's that appear in the PCT_EPO list but not in the EPO list above
PCT_EPO_list = list(PCT_EPO_notEPO["pct_nbr"])
#extract only PCT results that have a corresponding EPO number but are not duplicated above
PCT_all_EPO = PCT_all[PCT_all["pct_nbr"].isin(PCT_EPO_list)]

In [32]:
#for the PCT IPC database we want only the first result
def first(s):
    return s.iloc[0]
    
IPC_first_PCT = PCT_IPC.groupby(["pct_nbr"]).agg(first)

In [33]:
#merge the results from above with the IPC database
PCT_IPC_all_EPO = PCT_all_EPO.merge(IPC_first_PCT, on = "pct_nbr")

In [34]:
#check the result
PCT_IPC_all_EPO

              pct_nbr  prio_year  app_year           IPC
0        WO2013091521       2011      2012    C07F009/53
1        WO2019084426       2017      2018    A61M029/00
2        WO2010045609       2008      2009    B65G045/00
3        WO2019098131       2017      2018    G02B005/08
4        WO2004085669       2003      2004    C12Q001/68
5        WO2016184213       2015      2016    H04L009/32
6        WO2001061289       2000      2001    G01G023/37
7        WO2014073190       2012      2013    H01G011/26
8        WO2017203410       2016      2017    H01H009/02
9        WO2005015965       2003      2004    H05K001/09
10       WO2018172321       2017      2018    C23C016/40
11       WO2005097476       2004      2005    B29C041/02
12       WO2006030786       2004      2005    G01H017/00
13       WO2008039512       2006      2007    H04L029/06
14       WO2017074126       2015      2016    F24F006/00
15       WO2006040985       2004      2005    H01M008/02
16       WO2010027416       2008      2009    A46B015/00
17       WO2016097773       2014      2015    A61P035/02
18       WO2015058987       2013      2014   A61M005/172
19       WO2016025103       2014      2015    G08G001/16
20       WO2016194626       2015      2016   H02M003/155
21       WO2017200245       2016      2017    F21K009/65
22       WO2017058955       2015      2016    G07F017/32
23       WO2019025892       2017      2018    A61N005/06
24       WO2018109640       2016      2017    A61B003/13
25       WO2011126490       2010      2010    A61F002/44
26       WO2007109073       2006      2007    A61B017/22
27       WO2019056512       2017      2017    H01L027/12
28       WO1991009646       1989      1990    G03F007/20
29       WO2001050457       1999      2000    G10L019/02
...               ...        ...       ...           ...
1790474  WO2009053514       2007      2008   A61K039/395
1790475  WO2003091555       2002      2003    F02B053/14
1790476  WO2017105597       2015      2016    G06F015/78
1790477  WO2011140200       2010      2011   H01J037/317
1790478  WO2001084017       2000      2001    F16H047/08
1790479  WO2014041606       2012      2012    H04R031/00
1790480  WO2003056315       2001      2002  G02F001/1333
1790481  WO2013178719       2012      2013    B61F005/08
1790482  WO2003086361       2002      2002  A61K031/4178
1790483  WO2015190723       2014      2015    H01J037/26
1790484  WO2015149262       2014      2014    H02J007/32
1790485  WO2018163116       2017      2018   A61C003/025
1790486  WO2018223349       2017      2017    H04W024/00
1790487  WO2017101802       2015      2016    F24C011/00
1790488  WO2006083613       2005      2006    A47J031/00
1790489  WO2013181902       2012      2012   H01L021/335
1790490  WO2015054475       2013      2014    B26B021/40
1790491  WO2005101180       2004      2005    G06F003/06
1790492  WO2018023447       2016      2016    B66B001/14
1790493  WO2018158739       2017      2018    B05D003/06
1790494  WO1993003745       1991      1992    A61K047/02
1790495  WO2018227515       2017      2017    A61Q005/12
1790496  WO1999016152       1997      1998   H01R013/631
1790497  WO2005037561       2003      2004   G06F003/033
1790498  WO2015154209       2014      2014    C12P013/06
1790499  WO1998030825       1997      1998   F16L037/092
1790500  WO1994006300       1992      1993    A21C011/04
1790501  WO2011163246       2010      2011    G01C021/16
1790502  WO2013161577       2012      2013    H01L021/66
1790503  WO2010030616       2008      2009   H01R013/627

[1790504 rows x 4 columns]

## Merge the two

Once both potential citations have been identified, they must be merged in order to make sure that the controls are representative of the complete set of data that is available.

In [35]:
#we then want to combine both the EPO data and the IPC data 
#this is so that any control choice depends not only on EPO data but also IPC at the same time
#this reduces any potential bias in the results
combined = pd.concat([all_EPO_IPC, PCT_IPC_all_EPO], axis = 0)

C:\Users\cex\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [36]:
#check the combined results
combined

                  IPC  app_year    appln_id       pct_nbr  prio_year
0          A01N025/02      1989  16777216.0           NaN       1988
1          G06K007/00      2000         1.0           NaN       1999
2          C07K014/00      1992         2.0           NaN       1991
3          G01T001/00      2000         3.0           NaN       1999
4          H01L021/60      2000         4.0           NaN       1999
5          H01L021/28      2000         5.0           NaN       1999
6          H04L012/00      2000         6.0           NaN       1999
7          H04L012/28      2000         7.0           NaN       1999
8          B01D053/86      2000         8.0           NaN       2000
9          A62C031/02      2000         9.0           NaN       1999
10         B01J023/46      2001        10.0           NaN       2000
11         F15B021/04      2001        11.0           NaN       2000
12         B01J021/10      2001        12.0           NaN       2000
13         G06F001/06      2001        13.0           NaN       2000
14         F01P007/04      2001        14.0           NaN       2000
15         A61K009/06      2001        15.0           NaN       2000
16         A23L001/30      2001        16.0           NaN       2000
17         B05B011/00      2001        17.0           NaN       2000
18         G01N031/10      2002        18.0           NaN       2001
19         A41C003/00      2002        19.0           NaN       2001
20         E02B011/02      2002        20.0           NaN       2001
21         C09K011/77      2002        21.0           NaN       2001
22         H04B003/23      2002        22.0           NaN       2001
23         A45D019/00      2002        23.0           NaN       2001
24         B01J003/00      2002        24.0           NaN       2001
25        A23L001/305      2002        25.0           NaN       2001
26         H01F001/00      2002        26.0           NaN       2001
27         A61K009/20      2002        27.0           NaN       2001
28         B60J005/04      2002        28.0           NaN       2001
29         G01D005/24      2002        29.0           NaN       2001
...               ...       ...         ...           ...        ...
1790474   A61K039/395      2008         NaN  WO2009053514       2007
1790475    F02B053/14      2003         NaN  WO2003091555       2002
1790476    G06F015/78      2016         NaN  WO2017105597       2015
1790477   H01J037/317      2011         NaN  WO2011140200       2010
1790478    F16H047/08      2001         NaN  WO2001084017       2000
1790479    H04R031/00      2012         NaN  WO2014041606       2012
1790480  G02F001/1333      2002         NaN  WO2003056315       2001
1790481    B61F005/08      2013         NaN  WO2013178719       2012
1790482  A61K031/4178      2002         NaN  WO2003086361       2002
1790483    H01J037/26      2015         NaN  WO2015190723       2014
1790484    H02J007/32      2014         NaN  WO2015149262       2014
1790485   A61C003/025      2018         NaN  WO2018163116       2017
1790486    H04W024/00      2017         NaN  WO2018223349       2017
1790487    F24C011/00      2016         NaN  WO2017101802       2015
1790488    A47J031/00      2006         NaN  WO2006083613       2005
1790489   H01L021/335      2012         NaN  WO2013181902       2012
1790490    B26B021/40      2014         NaN  WO2015054475       2013
1790491    G06F003/06      2005         NaN  WO2005101180       2004
1790492    B66B001/14      2016         NaN  WO2018023447       2016
1790493    B05D003/06      2018         NaN  WO2018158739       2017
1790494    A61K047/02      1992         NaN  WO1993003745       1991
1790495    A61Q005/12      2017         NaN  WO2018227515       2017
1790496   H01R013/631      1998         NaN  WO1999016152       1997
1790497   G06F003/033      2004         NaN  WO2005037561       2003
1790498    C12P013/06      2014         NaN  WO2015154209       2014
1790499   F16L037/092      1998         NaN  WO1998030825       1997
1790500    A21C011/04      1993         NaN  WO1994006300       1992
1790501    G01C021/16      2011         NaN  WO2011163246       2010
1790502    H01L021/66      2013         NaN  WO2013161577       2012
1790503   H01R013/627      2009         NaN  WO2010030616       2008

[5297895 rows x 5 columns]

In [ ]:
#output this to a new csv to be merged later on with the actual citations
combined.to_csv("Patents data/potential_control.csv",index = False)